#pragma config(Sensor, dgtl2,  leftSonar,      sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  rightSonar,     sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           aftMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

typedef int tArray[100][0];
int rotSpeed = 127, forwdSpeed = 127, sfArmSpeed = 63;
int tIntvl = 30;
tArray surround1;
tArray surround2;

typedef struct
{
	int min;
	int minNum;
}toVal;

toVal twoVal;

void getMin(tArray x)
{
	for(int i = 0; i < sizeof(x); i++)
	{
		if(twoVal.min > x[i])
		{
			twoVal.min = x[i];
			twoVal.minNum = i;
		}
	}
}

task main()
{
	int i = 0;
		ClearTimer(T1);
		do{

			if(time1[T1] > tIntvl)
			{
				surround1[i] = SensorValue[leftSonar];
				surround2[i] = SensorValue[rightSonar];


				i++;
				ClearTimer(T1);
			}

			motor[leftMotor] = rotSpeed;
			motor[rightMotor] = -rotSpeed;
			motor[aftMotor] = rotSpeed;

	}while(surround1[99] != 0);

getMin(surround1);

int min1 = twoVal.min;
int minNum1 = twoVal.minNum;

getMin(surround2);

int min2 = twoVal.min;
int minNum2 = twoVal.minNum;

bool one = NULL;

if(min1 < min2){
			one = true;
			motor[leftMotor] = rotSpeed;
			motor[rightMotor] = -rotSpeed;
			motor[aftMotor] = rotSpeed;
			wait1Msec(minNum1*tIntvl);

}
else if(min2 < min1){
			one = false;
			motor[leftMotor] = rotSpeed;
			motor[rightMotor] = -rotSpeed;
			motor[aftMotor] = rotSpeed;
			wait1Msec(minNum2*tIntvl);

}

motor[leftMotor] = forwdSpeed;
motor[rightMotor] = forwdSpeed;
if(one)
	wait1Msec(min1);

else
	wait1Msec(min2);


}
